
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'AB8A82635A284FAC5ED6C8345E8A9B39'
    
_lr_action_items = {'NAME':([0,5,8,9,10,11,12,14,15,16,17,18,26,27,],[2,2,2,2,2,2,-1,24,24,-4,-2,2,-5,-3,]),')':([1,2,4,7,13,19,20,21,22,23,24,25,],[-8,-15,-14,-12,22,-7,-6,-9,-13,-10,-15,-11,]),'(':([0,5,8,9,10,11,12,14,15,16,17,18,26,27,],[5,5,5,5,5,5,-1,5,5,-4,-2,5,-5,-3,]),'+':([1,2,4,7,22,23,24,25,],[10,-15,-14,-12,-13,-10,-15,-11,]),'*':([2,4,7,22,24,],[-15,-14,14,-13,-15,]),'-':([1,2,4,7,22,23,24,25,],[9,-15,-14,-12,-13,-10,-15,-11,]),'}':([8,12,16,17,18,26,27,],[17,-1,-4,-2,27,-5,-3,]),'/':([2,4,7,22,24,],[-15,-14,15,-13,-15,]),'NUM':([0,5,8,9,10,11,12,14,15,16,17,18,26,27,],[4,4,4,4,4,4,-1,4,4,-4,-2,4,-5,-3,]),'{':([0,8,12,16,17,18,26,27,],[8,8,-1,-4,-2,8,-5,-3,]),'=':([2,],[11,]),';':([1,2,3,4,7,19,20,21,22,23,24,25,],[-8,-15,12,-14,-12,-7,-6,-9,-13,-10,-15,-11,]),'$end':([6,12,17,27,],[0,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,5,8,9,10,11,18,],[3,13,3,19,20,21,3,]),'term':([0,5,8,9,10,11,14,15,18,],[1,1,1,1,1,1,23,25,1,]),'block_item_list':([8,],[18,]),'statement':([0,8,18,],[6,16,26,]),'factor':([0,5,8,9,10,11,14,15,18,],[7,7,7,7,7,7,7,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expr ;','statement',2,'p_statement_a','LargeProject2.py',112),
  ('statement -> { }','statement',2,'p_statement_b','LargeProject2.py',116),
  ('statement -> { block_item_list }','statement',3,'p_statement_c','LargeProject2.py',123),
  ('block_item_list -> statement','block_item_list',1,'p_block_item_list_a','LargeProject2.py',130),
  ('block_item_list -> block_item_list statement','block_item_list',2,'p_block_item_list_b','LargeProject2.py',134),
  ('expr -> term + expr','expr',3,'p_expr_a','LargeProject2.py',139),
  ('expr -> term - expr','expr',3,'p_expr_b','LargeProject2.py',146),
  ('expr -> term','expr',1,'p_expr_c','LargeProject2.py',153),
  ('expr -> NAME = expr','expr',3,'p_expr_d','LargeProject2.py',157),
  ('term -> factor * term','term',3,'p_term_a','LargeProject2.py',164),
  ('term -> factor / term','term',3,'p_term_b','LargeProject2.py',171),
  ('term -> factor','term',1,'p_term_c','LargeProject2.py',178),
  ('factor -> ( expr )','factor',3,'p_factor_a','LargeProject2.py',182),
  ('factor -> NUM','factor',1,'p_factor_b','LargeProject2.py',186),
  ('factor -> NAME','factor',1,'p_factor_c','LargeProject2.py',193),
]
